[package]
name = "satansfiddle"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.5", features = ["derive"] }
digest-io = "0.1.0"
hex = "0.4"
hex-literal = "0.4.1"
lldb = { path = "libs/codelldb/src/lldb", features = ["no_link_args"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.11.0"
shlex = "2.0.1"
toml = "0.8"
